In [44]:
#Programs on selection and Iteration operations
'''Get an integer input from a user. If the number is odd, then find the 
factorial of a number and find the number of digits in the factorial of the
number. If the number is even, then check the given number is palindrome 
or not'''
def main():
    n = int(input("Enter an integer: "))
    factorial_of_n = 1
    number_of_digits_in_factorial = 0
    if n % 2 == 1:
        for i in range(1, n + 1):
            factorial_of_n *= i
            number_of_digits_in_factorial += 1
        print("The factorial of {} is {} and it has {} digits.".format(n, factorial_of_n, number_of_digits_in_factorial))
    else:
        reversed_number = 0
        temp = n
        while temp > 0:
            reversed_number *= 10
            reversed_number += temp % 10
            temp //= 10
        is_palindrome_number = n == reversed_number
        print("The number {} is {} a palindrome.".format(n, "not" if not is_palindrome_number else ""))

if __name__ == "__main__":
    main()


Enter an integer: 3
The factorial of 3 is 6 and it has 3 digits.


In [45]:
#Strings and its operations
'''Given two strings, PRINT (YES or NO) whether the second string can be 
obtained from the first by deletion of none, one or more characters.'''

def main():
    str_1 = "hello"
    str_2 = "ello"
    str_2_index = 0
    for char in str_1:
        if char == str_2[str_2_index]:
            str_2_index += 1
        else:
            if str_2_index == 0:
                print("NO")
                break
            else:
                str_2_index = 0
    else:
        print("YES")

if __name__ == "__main__":
    main()

NO


In [46]:
# List and its operations
'''Programs for positive and negative indexing'''

list_of_numbers = [1, 2, 3, 4, 5]

first_element = list_of_numbers[0]
second_element = list_of_numbers[1]
last_element = list_of_numbers[-1]

print(first_element)
print(second_element)
print(last_element)


1
2
5


In [1]:
'''Program to check if the given list is in Ascending order or not.'''

def is_ascending(list1):
 
  for i in range(len(list1) - 1):
    if list1[i] > list1[i + 1]:
      return False
  return True

list1 = [1, 2, 3, 4, 5]
print(is_ascending(list1))  # True

list2 = [5, 4, 3, 2, 1]
print(is_ascending(list2))  # False


True
False


In [48]:
#Tuples and its operations
'''Python program to convert a tuple to a string'''

tuple1 = (1, 2, 3, 4, 5)
string1 = ""
for element in tuple1:
  string1 += str(element)
print(string1)


12345


In [49]:
''' Python program to reverse a tuple'''

tuple1 = (1, 2, 3, 4, 5)
reversed_tuple = tuple(list(tuple1)[::-1])
print(reversed_tuple)


(5, 4, 3, 2, 1)


In [50]:
#Sets and its operations
'''Python program to check if a set is a subset of another set'''

set1 = {1, 2, 3, 4, 5}
set2 = {1, 2, 3, 4, 5, 6, 7, 8, 9}

is_subset = True
for element in set1:
  if element not in set2:
    is_subset = False
    break

print(is_subset)

set3 = {1, 2, 3}
is_subset = True
for element in set3:
  if element not in set2:
    is_subset = False
    break

print(is_subset)


True
True


In [51]:
# Dictionaries and its operations Python program to iterate over dictionaries using for loops

dict1 = {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

for key, value in dict1.items():
  print(f"key: {key}, value: {value}")


key: key1, value: value1
key: key2, value: value2
key: key3, value: value3


In [52]:
#Computations using NumPy functions
''' NumPy program to convert a list of numeric value into 
a one-dimensional NumPy array'''

import numpy as np
list1 = [1, 2, 3, 4, 5]

array1 = np.array(list1)

print(array1)


[1 2 3 4 5]


In [53]:
''' NumPy program to convert a list and tuple into arrays. 
Data manipulations using Pandas'''

import numpy as np
import pandas as pd

list1 = [1, 2, 3, 4, 5]
tuple1 = (1, 2, 3, 4, 5)

array1 = np.array(list1)
array2 = np.array(tuple1)

print(array1)  # array([1, 2, 3, 4, 5])
print(array2)  # array([1, 2, 3, 4, 5])

df = pd.DataFrame({'list': list1, 'tuple': tuple1})

print(df)
   
df['list'] += 10
df['tuple'] += 10

print(df)

[1 2 3 4 5]
[1 2 3 4 5]
   list  tuple
0     1      1
1     2      2
2     3      3
3     4      4
4     5      5
   list  tuple
0    11     11
1    12     12
2    13     13
3    14     14
4    15     15


In [54]:
'''Program to convert a NumPy array and series to data frames.
'''

import numpy as np
import pandas as pd

array1 = np.array([1, 2, 3, 4, 5])
series1 = pd.Series([1, 2, 3, 4, 5])

df1 = pd.DataFrame(array1)
df2 = pd.DataFrame(series1)

print(df1)
   

print(df2)
    

   0
0  1
1  2
2  3
3  4
4  5
   0
0  1
1  2
2  3
3  4
4  5


In [55]:
''' Program to add, subtract, multiple and divide two Pandas Series'''

import numpy as np
import pandas as pd

series1 = pd.Series([1, 2, 3, 4, 5])
series2 = pd.Series([6, 7, 8, 9, 10])

addition = series1 + series2
subtraction = series1 - series2
multiplication = series1 * series2
division = series1 / series2

print(addition)
   
print(subtraction)

print(multiplication)

print(division)

0     7
1     9
2    11
3    13
4    15
dtype: int64
0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64
0     6
1    14
2    24
3    36
4    50
dtype: int64
0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64


In [56]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'Name': ['Sulav Shrestha', 'AAsish Shrestha', 'Kumar Chaudhary', 'Bibek Chaudhary'], 'Age': [20, 20, 19, 18], 'Country': ['USA', 'Canada', 'UK', 'Australia']})

name = df['Name'].iloc[0]

age = df['Age'].iloc[1]

country = df['Country'].iloc[2]

print(name)
print(age)
print(country)

df['Salary'] = np.random.randint(20000, 50000, size=4)

print(df)


Sulav Shrestha
20
UK
              Name  Age    Country  Salary
0   Sulav Shrestha   20        USA   40864
1  AAsish Shrestha   20     Canada   40011
2  Kumar Chaudhary   19         UK   26495
3  Bibek Chaudhary   18  Australia   39204
